use_highlight_loss: true
highlight_loss_func: ${model.func_highlight}

grounding_loss_func: ${model.func_grounding}

use_dn_loss: true
dn_loss_func: ${model.func_dn}
dn_kl_loss_func: ${model.func_dn_kl}
